from .clock.clock import ClockWidget
from .cpu import CPUWidget
from .ram import RAMWidget
from .log import LogWidget
from .bitrate import BitrateWidget
from .battery import BatteryWidget
from .direct_button import DirectButton
from .develop_button import DevelopButton
from .foldr_button import FolderButton
from .exchange import ExchangeWidget
from .wifi import WifiWidget
#from picture.picture import PictureWidget